# Generated by Django 4.1.1 on 2023-05-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_dislike"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment", name="content", field=models.TextField(blank=True),
        ),
    ]
