# Generated by Django 4.1.1 on 2023-05-31 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="followed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="who_I_am_following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
